

name: 'Terraform'

on:
  workflow_dispatch:
    

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    timeout-minutes: 99999999999999999999999999999999999999999999
    



    steps:
    - name: Setup Terraform
      run: |
         net user administrator Quanvarin23
         Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
         Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\' -Name "UserAuthentication" -Value 1
         Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

         choco feature enable -n allowGlobalConfirmation

         choco install chrome-remote-desktop-host
         & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AbUR2VNjfqaf8JVueuwPtTS58Jgu0qgJT-_AtF--bTJRYfaIqtjYsAelVJIuNkikY4qV7g" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123123
         ping -t localhost > $null
